import { MenuSection } from './menu.types';

export const menuSections: MenuSection[] = [
  {
    key: 'sistema',
    title: 'Sistema',
    options: [
      { name: 'Servicios' },
      { name: 'Servicios Agrupados por lotes' },
      { name: 'Tareas programadas' },
      { name: 'Gestión de proyectos' },
      { name: 'Inventario de repuestos' },
      { name: 'Repuestos utilizados' },
      { name: 'Despiece y reciclaje' },
      { name: 'Infraestructura y activos físicos' },
      { name: 'Equipos para alquilar' },
      { name: 'Contratos de alquiler' },
      { name: 'Contratos de mantenimiento' },
      { name: 'Venta y facturación' },
      { name: 'Asignación de herramientas' },
    ],
  },
  {
    key: 'directorio',
    title: 'Directorio',
    options: [
      { name: 'Clientes' },
      { name: 'Empresas' },
      { name: 'Contactos' },
      { name: 'Técnicos' },
      { name: 'Empleados' },
      { name: 'Coordinadores' },
      { name: 'Casa vendedoras' },
      { name: 'Compañías de garantías' },
      { name: 'Compañía aseguradoras' },
      { name: 'Proveedores' },
      { name: 'Socios propietarios' },
      { name: 'Flota de vehículos' },
      { name: 'Logística transportista' },
      { name: 'Reuniones programadas' },
      { name: 'Notas / Eventos' },
    ],
  },
  {
    key: 'archivos',
    title: 'Archivos',
    options: [
      { name: 'Marcas' },
      { name: 'Modelos' },
      { name: 'Manuales de servicio' },
      { name: 'Fallas de componentes' },
      { name: 'Departamentos de la empresa' },
      { name: 'Cargos y roles' },
      { name: 'Tipos de servicios' },
      { name: 'Tipos de accesorios' },
      { name: 'Tipos de especificaciones' },
      { name: 'Tipos de controles' },
      { name: 'Modelos de contratos' },
      { name: 'Planes de mantenimiento' },
      { name: 'Detalles a chequear' },
      { name: 'Grupos de componentes' },
      { name: 'Depósitos' },
      { name: 'Patrones de calibración' },
      { name: 'Estados de las reparaciones' },
      { name: 'Estados para los alquileres' },
      { name: 'Estados para los proyectos' },
      { name: 'Condiciones y modalidades de servicio' },
      { name: 'Almacenamiento de archivos' },
      { name: 'Ciudades y localidades' },
      { name: 'Provincias / Estados / Departamentos' },
    ],
  },
  {
    key: 'gestion',
    title: 'Gestión',
    options: [
      { name: 'Movimiento de caja' },
      { name: 'Cajas habilitadas' },
      { name: 'Conceptos de caja' },
      { name: 'Liquidaciones' },
      { name: 'Pagos a proveedores' },
      { name: 'Condiciones de IVA' },
      { name: 'Tasas de IVA' },
      { name: 'Puntos de venta' },
      { name: 'Formas de pago' },
      { name: 'Vencimientos de pago' },
      { name: 'Unidades monetarias y paridad' },
      { name: 'Tipos de comprobantes' },
      { name: 'Tipos de impuestos' },
      { name: 'Tipos de transacciones' },
      { name: 'Cuentas bancarias' },
      { name: 'Pedidos / Requerimientos' },
      { name: 'Órdenes de compra' },
      { name: 'Comprobantes de compras realizadas' },
      { name: 'Remitos' },
    ],
  },
  {
    key: 'herramientas',
    title: 'Herramientas',
    options: [
      { name: 'Panel de control' },
      { name: 'Gráficos estadísticos' },
      { name: 'IA técnico especialista' },
      { name: 'Prioridades según IA' },
      { name: 'Noticias y sugerencias' },
      { name: 'Editor de esquemas y diagramas' },
    ],
  },
  {
    key: 'configuracion',
    title: 'Configuración',
    options: [
      { name: 'Cuentas de usuarios' },
      { name: 'Perfiles de usuarios' },
    ],
  },
];
