export const MENU_STRUCTURE = {
  sistema: {
    title: 'Sistema',
    icon: '⚙️',
    items: [
      { name: 'Servicios', href: '/sistema/servicios' },
      { name: 'Servicios Agrupados por lotes', href: '/sistema/servicios-lotes' },
      { name: 'Tareas programadas', href: '/sistema/tareas' },
      { name: 'Gestión de proyectos', href: '/sistema/proyectos' },
      { name: 'Inventario de repuestos', href: '/sistema/inventario' },
      { name: 'Repuestos utilizados', href: '/sistema/repuestos-usados' },
      { name: 'Despiece y reciclaje', href: '/sistema/despiece' },
      { name: 'Infraestructura y activos', href: '/sistema/infraestructura' },
      { name: 'Equipos para alquilar', href: '/sistema/equipos-alquiler' },
      { name: 'Contratos de alquiler', href: '/sistema/contratos-alquiler' },
      { name: 'Contratos de mantenimiento', href: '/sistema/contratos-mantenimiento' },
      { name: 'Venta y facturación', href: '/sistema/facturacion' },
      { name: 'Asignación de herramientas', href: '/sistema/herramientas' },
    ],
  },
  directorio: {
    title: 'Directorio',
    icon: '📋',
    items: [
      { name: 'Clientes', href: '/directorio/clientes' },
      { name: 'Empresas', href: '/directorio/empresas' },
      { name: 'Contactos', href: '/directorio/contactos' },
      { name: 'Técnicos', href: '/directorio/tecnicos' },
      { name: 'Empleados', href: '/directorio/empleados' },
      { name: 'Coordinadores', href: '/directorio/coordinadores' },
      { name: 'Casas vendedoras', href: '/directorio/casas-vendedoras' },
      { name: 'Compañías de garantías', href: '/directorio/garantias' },
      { name: 'Compañías aseguradoras', href: '/directorio/aseguradoras' },
      { name: 'Proveedores', href: '/directorio/proveedores' },
      { name: 'Socios propietarios', href: '/directorio/socios' },
      { name: 'Flota de vehículos', href: '/directorio/vehiculos' },
      { name: 'Logística transportista', href: '/directorio/logistica' },
      { name: 'Reuniones programadas', href: '/directorio/reuniones' },
      { name: 'Notas / Eventos', href: '/directorio/eventos' },
    ],
  },
  archivos: {
    title: 'Archivos',
    icon: '📁',
    items: [
      { name: 'Marcas', href: '/archivos/marcas' },
      { name: 'Modelos', href: '/archivos/modelos' },
      { name: 'Manuales de servicio', href: '/archivos/manuales' },
      { name: 'Fallas de componentes', href: '/archivos/fallas' },
      { name: 'Departamentos', href: '/archivos/departamentos' },
      { name: 'Cargos y roles', href: '/archivos/cargos' },
      { name: 'Tipos de servicios', href: '/archivos/tipos-servicios' },
      { name: 'Tipos de accesorios', href: '/archivos/tipos-accesorios' },
      { name: 'Tipos de especificaciones', href: '/archivos/tipos-especificaciones' },
      { name: 'Tipos de controles', href: '/archivos/tipos-controles' },
      { name: 'Modelos de contratos', href: '/archivos/modelos-contratos' },
      { name: 'Planes de mantenimiento', href: '/archivos/planes' },
      { name: 'Detalles a chequear', href: '/archivos/detalles-chequeo' },
      { name: 'Grupos de componentes', href: '/archivos/grupos-componentes' },
      { name: 'Depósitos', href: '/archivos/depositos' },
      { name: 'Patrones de calibración', href: '/archivos/calibracion' },
      { name: 'Estados de reparaciones', href: '/archivos/estados-reparacion' },
      { name: 'Estados para alquileres', href: '/archivos/estados-alquiler' },
      { name: 'Estados para proyectos', href: '/archivos/estados-proyecto' },
      { name: 'Condiciones de servicio', href: '/archivos/condiciones' },
      { name: 'Almacenamiento de archivos', href: '/archivos/storage' },
      { name: 'Ciudades y localidades', href: '/archivos/ciudades' },
      { name: 'Provincias / Departamentos', href: '/archivos/provincias' },
    ],
  },
  gestion: {
    title: 'Gestión',
    icon: '💰',
    items: [
      { name: 'Movimiento de caja', href: '/gestion/caja' },
      { name: 'Cajas habilitadas', href: '/gestion/cajas' },
      { name: 'Conceptos de caja', href: '/gestion/conceptos-caja' },
      { name: 'Liquidaciones', href: '/gestion/liquidaciones' },
      { name: 'Pagos a proveedores', href: '/gestion/pagos' },
      { name: 'Condiciones de IVA', href: '/gestion/condiciones-iva' },
      { name: 'Tasas de IVA', href: '/gestion/tasas-iva' },
      { name: 'Puntos de venta', href: '/gestion/puntos-venta' },
      { name: 'Formas de pago', href: '/gestion/formas-pago' },
      { name: 'Vencimientos de pago', href: '/gestion/vencimientos' },
      { name: 'Unidades monetarias', href: '/gestion/monedas' },
      { name: 'Tipos de comprobantes', href: '/gestion/comprobantes' },
      { name: 'Tipos de impuestos', href: '/gestion/impuestos' },
      { name: 'Tipos de transacciones', href: '/gestion/transacciones' },
      { name: 'Cuentas bancarias', href: '/gestion/cuentas-bancarias' },
      { name: 'Pedidos / Requerimientos', href: '/gestion/pedidos' },
      { name: 'Órdenes de compra', href: '/gestion/ordenes-compra' },
      { name: 'Comprobantes de compra', href: '/gestion/comprobantes-compra' },
      { name: 'Remitos', href: '/gestion/remitos' },
    ],
  },
  herramientas: {
    title: 'Herramientas',
    icon: '🛠️',
    items: [
      { name: 'Panel de control', href: '/herramientas/dashboard' },
      { name: 'Gráficos estadísticos', href: '/herramientas/graficos' },
      { name: 'IA técnico especialista', href: '/herramientas/ia' },
      { name: 'Prioridades según IA', href: '/herramientas/prioridades' },
      { name: 'Noticias y sugerencias', href: '/herramientas/noticias' },
      { name: 'Editor de esquemas', href: '/herramientas/editor' },
    ],
  },
  configuracion: {
    title: 'Configuración',
    icon: '⚡',
    items: [
      { name: 'Cuentas de usuarios', href: '/configuracion/usuarios' },
      { name: 'Perfiles de usuarios', href: '/configuracion/perfiles' },
    ],
  },
};

export const MENU_SECTIONS = Object.values(MENU_STRUCTURE);
